//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicaConsole.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryLogin
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Successfully { get; set; }
    
        public virtual User User { get; set; }
    }
}
