//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicaConsole.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryAut
    {
        public int Id { get; set; }
        public System.DateTime Datetime { get; set; }
        public int ReceptionService { get; set; }
    
        public virtual ReceptionService ReceptionService1 { get; set; }
    }
}
