//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicaConsole.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KlinicaDBEntities : DbContext
    {
        public KlinicaDBEntities()
            : base("name=KlinicaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cabinet> Cabinets { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<HoneyCard> HoneyCards { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Pfile> Pfiles { get; set; }
        public virtual DbSet<ReceptionService> ReceptionServices { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SocStatu> SocStatus { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TimeTable> TimeTables { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<WorkerFunction> WorkerFunctions { get; set; }
        public virtual DbSet<HistoryAut> HistoryAuts { get; set; }
        public virtual DbSet<HistoryLogin> HistoryLogins { get; set; }
    
        public virtual int DateStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DateStatus");
        }
    }
}
