//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicaConsole.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceptionService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceptionService()
        {
            this.HistoryAuts = new HashSet<HistoryAut>();
        }
    
        public int Id { get; set; }
        public string HoneyCardId { get; set; }
        public int TimeTibleId { get; set; }
        public string Protocol { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ServicesId { get; set; }
    
        public virtual HoneyCard HoneyCard { get; set; }
        public virtual Service Service { get; set; }
        public virtual TimeTable TimeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryAut> HistoryAuts { get; set; }
    }
}
