//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlinicaConsole.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkerFunction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkerFunction()
        {
            this.TimeTables = new HashSet<TimeTable>();
        }
    
        public int Id { get; set; }
        public int WorkerId { get; set; }
        public int FunctionId { get; set; }
    
        public virtual Function Function { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTable> TimeTables { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
