//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinica.Datebase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int WorkerId { get; set; }
        public int PfileId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> PatientId { get; set; }
        public string Comment { get; set; }
    
        public virtual DocumentsCategory DocumentsCategory { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Pfile Pfile { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
