//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinica.Datebase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabCatalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabCatalog()
        {
            this.LabResults = new HashSet<LabResult>();
        }
    
        public int Id { get; set; }
        public int WorkerId { get; set; }
        public int AppointId { get; set; }
        public System.DateTime DateTimeTaken { get; set; }
        public System.DateTime DateResultExpected { get; set; }
        public Nullable<System.DateTime> DateResultReal { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual WorkerFunction WorkerFunction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabResult> LabResults { get; set; }
    }
}
