//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinica.Datebase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabResult
    {
        public int Id { get; set; }
        public int LabCatalogId { get; set; }
        public string Result { get; set; }
        public string Comment { get; set; }
    
        public virtual LabCatalog LabCatalog { get; set; }
    }
}
