//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinica.Datebase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KlinicaDBEntities1 : DbContext
    {
        public KlinicaDBEntities1()
            : base("name=KlinicaDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<DescriptionVisit> DescriptionVisits { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentsCategory> DocumentsCategories { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<LabCatalog> LabCatalogs { get; set; }
        public virtual DbSet<LabResult> LabResults { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<PaymentAppointment> PaymentAppointments { get; set; }
        public virtual DbSet<PaymentHistory> PaymentHistories { get; set; }
        public virtual DbSet<Pfile> Pfiles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServicesCategory> ServicesCategories { get; set; }
        public virtual DbSet<SocStatu> SocStatus { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Timing> Timings { get; set; }
        public virtual DbSet<TimingSegmentation> TimingSegmentations { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<WorkerFunction> WorkerFunctions { get; set; }
    }
}
