//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinica.Datebase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentHistory()
        {
            this.PaymentAppointments = new HashSet<PaymentAppointment>();
        }
    
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Sum { get; set; }
        public int PatientId { get; set; }
        public int WorkerId { get; set; }
        public int Status { get; set; }
    
        public virtual Patient Patient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentAppointment> PaymentAppointments { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
