//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klinica.Datebase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAppointment
    {
        public int Id { get; set; }
        public int PaymontId { get; set; }
        public int AppointmentId { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual PaymentHistory PaymentHistory { get; set; }
    }
}
